// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unillanos.Evaluaciones.Infrastructure.Persistencia;

#nullable disable

namespace Unillanos.Evaluaciones.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(EvaluacionesDbContext))]
    partial class EvaluacionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unillanos.Evaluaciones.Domain.Entidades.Actividad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Corte")
                        .HasColumnType("int");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("RequiereEntrega")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Actividad", null, t =>
                        {
                            t.HasCheckConstraint("CK_Actividad_Corte", "[Corte] BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_Actividad_Peso", "[Peso] >= 0 AND [Peso] <= 100");
                        });
                });

            modelBuilder.Entity("Unillanos.Evaluaciones.Domain.Entidades.Calificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntregaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Retroalimentacion")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ActividadId", "EstudianteId")
                        .IsUnique();

                    b.ToTable("Calificacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Calificacion_Estado", "[Estado] IN ('BORRADOR', 'PUBLICADA')");

                            t.HasCheckConstraint("CK_Calificacion_Valor", "[Valor] >= 0 AND [Valor] <= 5");
                        });
                });

            modelBuilder.Entity("Unillanos.Evaluaciones.Domain.Entidades.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PesoCorte1")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PesoCorte2")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PesoCorte3")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ProfesorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfesorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Curso", null, t =>
                        {
                            t.HasCheckConstraint("CK_Curso_Pesos", "[PesoCorte1] >= 0 AND [PesoCorte2] >= 0 AND [PesoCorte3] >= 0");
                        });
                });

            modelBuilder.Entity("Unillanos.Evaluaciones.Domain.Entidades.CursoEstudiante", b =>
                {
                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CursoId", "EstudianteId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("CursoEstudiante", (string)null);
                });

            modelBuilder.Entity("Unillanos.Evaluaciones.Domain.Entidades.PublicacionCorte", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Corte")
                        .HasColumnType("int");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nota")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("CursoId", "EstudianteId", "Corte", "Version")
                        .IsUnique();

                    b.ToTable("PublicacionCorte", null, t =>
                        {
                            t.HasCheckConstraint("CK_PublicacionCorte_Corte", "[Corte] BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_PublicacionCorte_Nota", "[Nota] >= 0 AND [Nota] <= 5");
                        });
                });

            modelBuilder.Entity("Unillanos.Evaluaciones.Domain.Entidades.Actividad", b =>
                {
                    b.HasOne("Unillanos.Evaluaciones.Domain.Entidades.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unillanos.Evaluaciones.Domain.Entidades.Calificacion", b =>
                {
                    b.HasOne("Unillanos.Evaluaciones.Domain.Entidades.Actividad", null)
                        .WithMany()
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unillanos.Evaluaciones.Domain.Entidades.CursoEstudiante", b =>
                {
                    b.HasOne("Unillanos.Evaluaciones.Domain.Entidades.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Unillanos.Evaluaciones.Domain.Entidades.PublicacionCorte", b =>
                {
                    b.HasOne("Unillanos.Evaluaciones.Domain.Entidades.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
