<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Evaluaciones.Infrastructure\Evaluaciones.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\compartido\Unillanos.ServiceDefaults\Unillanos.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
</Project>
