<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Unillanos.Evaluaciones.Api\Unillanos.Evaluaciones.Api.csproj" />
    <ProjectReference Include="..\..\..\compartido\Unillanos.Pruebas.Compartidas\Unillanos.Pruebas.Compartidas.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>
</Project>
