// <auto-generated />
using System;
using Entregas.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entregas.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(EntregasDbContext))]
    [Migration("20261002010705_ArchivosMultiples")]
    partial class ArchivosMultiples
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entregas.Domain.ArchivoEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("EntregaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("RutaBlob")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EntregaId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("UX_ArchivoEntrega_Entrega_Orden");

                    b.ToTable("ArchivoEntrega", (string)null);
                });

            modelBuilder.Entity("Entregas.Domain.Entrega", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("EstudianteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId")
                        .HasDatabaseName("IX_Entrega_Estudiante");

                    b.HasIndex("ActividadId", "EstudianteId")
                        .IsUnique()
                        .HasDatabaseName("UX_Entrega_Actividad_Estudiante");

                    b.ToTable("Entrega", null, t =>
                        {
                            t.HasCheckConstraint("CK_Entrega_Estado", "[Estado] IN ('ENVIADA', 'ANULADA')");
                        });
                });

            modelBuilder.Entity("Entregas.Domain.ArchivoEntrega", b =>
                {
                    b.HasOne("Entregas.Domain.Entrega", null)
                        .WithMany("Archivos")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entregas.Domain.Entrega", b =>
                {
                    b.Navigation("Archivos");
                });
#pragma warning restore 612, 618
        }
    }
}
